### PR TITLE
Fix/range error

### PR DESCRIPTION
**Pull request by thdk**
This PR adds the same fix bwindels/exif-parser#27 from the original repo.

I've added a test with an example image where parsing it would fail before this fix.

### CODE REVIEW

**Comment by bpatrik** [comment]
Thank you!

**Comment by thdk** [comment]
You're welcome (and I was lucky the fix was there already :) ) 
Thanks for merging already, hopefully it can be released soon?

**Comment by bpatrik** [comment]
I published it under v0.2.2

**Comment by thdk** [comment]
super thanks!

**Pull request merged**
